---
- name: Define memcached_enablerepo.
  set_fact: memcached_enablerepo={{ __memcached_enablerepo }}
  when: memcached_enablerepo is not defined

- name: Install Memcached packages.
  yum: name={{ item }} state=present enablerepo={{ memcached_enablerepo }}
  with_items: memcached_packages

- name: Copy Memcached config.
  template:
    src: memcached.j2
    dest: /etc/sysconfig/memcached
    owner: root
    group: root
  notify: restart memcached
  when: memcached_config_use_template
